adapters:
  r2dbc:
    host: "${DB_HOST}"
    port: "${DB_PORT}"
    database: "${DB_NAME}"
    username: "${DB_USER}"
    password: "${DB_PASSWORD}"
    schema: "public"

server:
  port: 8080
spring:
  application:
    name: "crediya-auth-service"
  devtools:
    add-properties: false
  r2dbc:
    url: "r2dbc:postgresql://${adapters.r2dbc.host}:${adapters.r2dbc.port}/${adapters.r2dbc.database}"
    username: "${adapters.r2dbc.username}"
    password: "${adapters.r2dbc.password}"

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

routes:
  user:
    paths:
      saveUser: "/usuarios"

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  allow-credentials: true
  max-age: 3600